// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Alert struct {
	ID              string `json:"id" bson:"_id"`
	SystemWwn       string `json:"systemWWN"`
	Status          string `json:"status"`
	Severity        string `json:"severity"`
	Type            string `json:"type"`
	Count           int    `json:"count"`
	LastOccuredTime string `json:"lastOccuredTime"`
	Description     string `json:"description"`
}

type NewAlert struct {
	SystemWwn       string `json:"systemWWN"`
	Status          string `json:"status"`
	Severity        string `json:"severity"`
	Type            string `json:"type"`
	Count           int    `json:"count"`
	LastOccuredTime string `json:"lastOccuredTime"`
	Description     string `json:"description"`
}
